### ISSUE TITLE
can't get metrics to show up in prometheus

### ISSUE THREAD

**Issue by andig** [deathowl/go-metrics-prometheus#14]
Definitely something stupid I'm doing but can't figure it out. Prometheus shows all the default ones, but not the metrics from the `go-metrics` examples:

	prometheusRegistry := prometheus.NewRegistry()
	prometheusClient := prometheusmetrics.NewPrometheusProvider(metrics.DefaultRegistry, "", "", prometheusRegistry, 1*time.Second)
	go prometheusClient.UpdatePrometheusMetrics()

	http.Handle("/metrics", promhttp.Handler())
	log.Println("Beginning to serve on port :8080")
	log.Fatal(http.ListenAndServe("127.1:8080", nil))

If I create `promauto` metrics they appear. Any hint?

**Comment by keithknott26** [comment]
I had a similar problem , turns out i needed to run `go prometheusClient.UpdatePrometheusMetrics()` again once the metrics were registered.

**Comment by andig** [comment]
This is my entire code:

	c := metrics.NewCounter()
	metrics.Register("foo", c)
	c.Inc(47)

	g := metrics.NewGauge()
	metrics.Register("bar", g)
	g.Update(47)

	f := metrics.NewFunctionalGauge(func() int64 { return rand.Int63() })
	metrics.Register("func", f)

	s := metrics.NewExpDecaySample(1028, 0.015) // or metrics.NewUniformSample(1028)
	h := metrics.NewHistogram(s)
	metrics.Register("baz", h)
	h.Update(47)

	m := metrics.NewMeter()
	metrics.Register("quux", m)
	m.Mark(47)

	t := metrics.NewTimer()
	metrics.Register("bang", t)
	t.Time(func() {
		time.Sleep(time.Duration(rand.Int63n(100)) * time.Millisecond)
	})
	t.Update(47)

	// go metrics.Log(metrics.DefaultRegistry, 1*time.Second, log.New(os.Stderr, "metrics: ", log.Lmicroseconds))

	opsProcessed := promauto.NewCounter(prometheus.CounterOpts{
		Name: "myapp_processed_ops_total",
		Help: "The total number of processed events",
	})
	go func() {
		for {
			opsProcessed.Inc()
			time.Sleep(1 * time.Second)
		}
	}()

	prometheusRegistry := prometheus.NewRegistry()
	prometheusClient := prometheusmetrics.NewPrometheusProvider(metrics.DefaultRegistry, "", "", prometheusRegistry, 1*time.Second)
	go prometheusClient.UpdatePrometheusMetrics()

	http.Handle("/metrics", promhttp.Handler())
	log.Println("Beginning to serve on port :8080")
	log.Fatal(http.ListenAndServe("127.1:8080", nil))

The `Update` is run after the metrics are registered?

**Comment by keithknott26** [comment]
@andig,

Is go-metrics logging output to the console when you uncomment the go metrics.Log... line ? I can confirm the code in this repo does work, but I haven’t been able to spot what’s wrong with your code yet. 

If we can confirm that go metrics is logging to console then we know that’s not the problem. The problem could be the blanks you have set for the name and subsys? Mine aren’t blank in fact they’re set to the default in the repo. 

 Also what happens if you put a sleep for 5 seconds after you register the go-metrics and right before the go prometheusClient.UpdatePrometheusMetrics()? 

Keith

**Comment by andig** [comment]
> Is go-metrics logging output to the console when you uncomment the go metrics.Log... line

Yes it is and I can confirm that `UpdatePrometheusMetricsOnce` is updating the metrics. Only I can't find them in Prometheus. Maybe my mistake is on that side.

> The problem could be the blanks you have set for the name and subsys?

Doesn't matter.

> Also what happens if you put a sleep for 5 seconds after you register the go-metrics and right before the go prometheusClient.UpdatePrometheusMetrics()?

Didn't test but it has a 1sec time inside to re-run export anyway.

curl shows the custom metrics simply aren't exposed:

```
❯ curl localhost:8080/metrics
# HELP go_gc_duration_seconds A summary of the GC invocation durations.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 0
go_gc_duration_seconds{quantile="0.25"} 0
go_gc_duration_seconds{quantile="0.5"} 0
go_gc_duration_seconds{quantile="0.75"} 0
go_gc_duration_seconds{quantile="1"} 0
go_gc_duration_seconds_sum 0
go_gc_duration_seconds_count 0
...
```

**Comment by keithknott26** [comment]
Were you able to sort this out? you should try putting some print statements in to see if the metrics are being passed into MustRegister:

`g = prometheus.NewGauge(prometheus.GaugeOpts{
			Namespace: c.flattenKey(c.namespace),
			Subsystem: c.flattenKey(c.subsystem),
			Name:      c.flattenKey(name),
			Help:      name,
		})
fmt.Println(fmt.Sprintf("Namespace: %s, Subsys: %s, Name: %s, Help: %s", c.namespace, c.subsystem, name, name))
c.promRegistry.MustRegister(g)
		c.gauges[key] = g
`

**Comment by andig** [comment]
Couldn't solve it and finally gave up :/

**Comment by keithknott26** [comment]
I think its not working because you're not using the prometheus.DefaultRegisterer. Once I modified the code to use that, I now see the metrics appearing in the metrics endpoint. 

Here is the complete code:
```
package main

import (
	"log"
	"math/rand"
	"net/http"
	"time"

	prometheusmetrics "github.com/deathowl/go-metrics-prometheus"
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
	"github.com/prometheus/client_golang/prometheus/promhttp"
	"github.com/rcrowley/go-metrics"
)

func main() {
	c := metrics.NewCounter()
	metrics.GetOrRegister("foo", c)
	c.Inc(47)

	g := metrics.NewGauge()
	metrics.GetOrRegister("bar", g)
	g.Update(47)

	f := metrics.NewFunctionalGauge(func() int64 { return rand.Int63() })
	metrics.GetOrRegister("func", f)

	s := metrics.NewExpDecaySample(1028, 0.015) // or metrics.NewUniformSample(1028)
	h := metrics.NewHistogram(s)
	metrics.GetOrRegister("baz", h)
	h.Update(47)

	m := metrics.NewMeter()
	metrics.GetOrRegister("quux", m)
	m.Mark(47)

	t := metrics.NewTimer()
	metrics.GetOrRegister("bang", t)
	t.Time(func() {
		time.Sleep(time.Duration(rand.Int63n(100)) * time.Millisecond)
	})
	t.Update(47)

	// go metrics.Log(metrics.DefaultRegistry, 1*time.Second, log.New(os.Stderr, "metrics: ", log.Lmicroseconds))

	opsProcessed := promauto.NewCounter(prometheus.CounterOpts{
		Name: "myapp_processed_ops_total",
		Help: "The total number of processed events",
	})
	go func() {
		for {
			opsProcessed.Inc()
			time.Sleep(1 * time.Second)
		}
	}()

	//prometheusRegistry := prometheus.NewRegistry()
	prometheusClient := prometheusmetrics.NewPrometheusProvider(metrics.DefaultRegistry, "whatever", "something", prometheus.DefaultRegisterer, 1*time.Second)
	go prometheusClient.UpdatePrometheusMetrics()

	http.Handle("/metrics", promhttp.Handler())
	log.Println("Beginning to serve on port :8080")
	log.Fatal(http.ListenAndServe("127.1:8080", nil))

}
```

You'll notice that the following metrics show up on the endpoint:
```
# HELP whatever_something_bang bang
# TYPE whatever_something_bang gauge
whatever_something_bang 0.4
# HELP whatever_something_bar bar
# TYPE whatever_something_bar gauge
whatever_something_bar 47
# HELP whatever_something_baz baz
# TYPE whatever_something_baz gauge
whatever_something_baz 47
# HELP whatever_something_foo foo
# TYPE whatever_something_foo gauge
whatever_something_foo 47
# HELP whatever_something_func func
# TYPE whatever_something_func gauge
whatever_something_func 8.943859491831172e+17
# HELP whatever_something_quux quux
# TYPE whatever_something_quux gauge
whatever_something_quux 9.4
```

Hope this helps!
Keith

**Comment by andig** [comment]
> Hope this helps!

It does, thanks for following up!

I have not debugged in detail, but using the `prometheus.DefaultRegisterer` works. It seems the usage example from the README that suggests to use `prometheus.NewRegistry()` needs further work to actually function.

**Comment by deathowl** [comment]
Does this need any modifications in the code? If so please open a bug or a PR and i'm glad to merge it. Sorry pretty busy nowadays.

**Comment by andig** [comment]
@deathowl my problem is that the example code doesn't work- I can't comment *why* that is though hence no PR.

Example:

    prometheusRegistry := prometheus.NewRegistry()
    prometheusClient := prometheusmetrics.NewPrometheusProvider(metrics.DefaultRegistry, "", "", prometheusRegistry, 1*time.Second)
    go prometheusClient.UpdatePrometheusMetrics()

-> metrics don't show

Working version:

    //prometheusRegistry := prometheus.NewRegistry()
    prometheusClient := prometheusmetrics.NewPrometheusProvider(metrics.DefaultRegistry, "whatever", "something", prometheus.DefaultRegisterer, 1*time.Second)
    go prometheusClient.UpdatePrometheusMetrics()

-> metrics show

Key is the use of `prometheus.DefaultRegisterer`. Likes in https://github.com/deathowl/go-metrics-prometheus/issues/14#issuecomment-570029311 seem to indicate this is a confisuing issue for some new users.

**Comment by deathowl** [comment]
Updated Readme. Thanks for reporting the issue

**Comment by andig** [comment]
I think this is still confusing. Readme has `metricsRegistry` but it's not being used anywhere.
